### ISSUE TITLE
Change icon and group in task bar by instance

### ISSUE THREAD

**Issue by digitalsignalperson** [atomontage/chrome-private#3]
I just went through these
https://askubuntu.com/questions/493142/can-i-put-two-chrome-different-users-on-my-launcher
https://github.com/felipecrs/dotfiles/blob/master/scripts/create_alternative_chrome_shortcut.sh

and found the last script created a desktop file I could further modify to
- set the Name=Chromium-MyThing
- change the icon to distinguish from default chromium

Would be cool to integrate with chrome-private in some way ability to automagically change the chromium icon (blue, green, red, purple, ... etc.) and keep windows of the different instances grouped separately.

**Comment by atomontage** [comment]
chrome-private is fully based on Chrome command-line arguments. If you find a command-line argument that sets window color or icon, feel free to open a PR with that functionality added. I don't currently see one.

Alternatively, you can create different root profiles and configure them to have different themes. Then use those root profiles as 'configuration classes' to spawn ephemeral profiles from, depending on what you want to do.

**Comment by digitalsignalperson** [comment]
Here's some pieces of a solution I have...

The original icon: https://commons.wikimedia.org/wiki/File:Chromium_Logo.svg

Code to make as more alternative colors out of it as needed (could get creative here with different ways)

```python
import re
from colorsys import rgb_to_hls, hls_to_rgb

def change_svg_hue(file_path, new_file_path, new_hue):
    with open(file_path, 'r') as f:
        svg_content = f.read()
    for color in re.findall(r'stop-color:#([0-9a-fA-F]{6})', svg_content):
        r, g, b = [int(color[i:i+2], 16) / 255 for i in range(0, 6, 2)]
        h, l, s = rgb_to_hls(r, g, b)
        r_new, g_new, b_new = [int(x * 255) for x in hls_to_rgb(new_hue / 360.0 , l , s)]
        new_color = f'{r_new:02x}{g_new:02x}{b_new:02x}'
        svg_content = svg_content.replace(color,new_color)
    with open(new_file_path, 'w') as f:
        f.write(svg_content)

for i in range(9):
    new_hue = i * 40
    change_svg_hue("Chromium_Logo.svg", "Chromium_Logo_%02i.svg" % i, new_hue)
```
![image](https://user-images.githubusercontent.com/45611618/226497623-0f53c7ed-55f3-4a3f-ade5-7eca189c6f0c.png)


Then for each profile, write a desktop file to  `~/.local/share/applications/{ class_name }.desktop'` with this template:

```
[Desktop Entry]
Version=1.0
Name={ class_name }
GenericName=Web Browser
Exec=/usr/bin/chromium --class={ class_name } --user-data-dir={ profile_dir } %U
StartupNotify=true
Terminal=false
#Icon=chromium
Icon={icon_path}
Type=Application
Categories=Network;WebBrowser;
MimeType=application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/http;x-scheme-handler/https;
Actions=new-window;new-private-window;

[Desktop Action new-window]
Name=New Window
Exec=/usr/bin/chromium --class={ class_name } --user-data-dir={ profile_dir }

[Desktop Action new-private-window]
Name=New Incognito Window
Exec=/usr/bin/chromium --class={ class_name } --user-data-dir={ profile_dir } --incognito
```

where I have
- profile_dir = the chromium profile path
- class_name = 'Chromium-' + profile_name (e.g. Chromium-Entertainment)
- icon_path = the path of the specific colored icon

And then I can launch the different chromium profiles and they show the different colored logos in the task manager and window titlebar.
